" Custom plugins
call plug#begin('~/.config/nvim/plugged')

" Indicate added, modified and removed lines managed by VCS :: vim-gitgutter
" https://github.com/airblade/vim-gitgutter
Plug 'airblade/vim-gitgutter'

" Colour theme :: Oceanic-Next.vim
" https://github.com/mhartington/oceanic-next
Plug 'mhartington/oceanic-next'

" JavaScript syntax :: YAJS: Yet Another JavaScript Syntax
" https://github.com/othree/yajs.vim
Plug 'othree/yajs.vim'

" html5.vim
Plug 'othree/html5.vim'

" Lint engine :: ALE: Asynchronous Lint Engine
" https://github.com/w0rp/ale
Plug 'w0rp/ale'

" Asynchronous keyword completion :: deoplete.nvim
" https://github.com/Shougo/deoplete.nvim
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }

" Python autocompletion :: jedi-vim
" https://github.com/davidhalter/jedi-vim
Plug 'davidhalter/jedi-vim'
" Python async autocompletion in NVim :: deoplete-jedi
" https://github.com/zchee/deoplete-jedi
Plug 'zchee/deoplete-jedi'

" End custom plugins and initialize plugin system
call plug#end()


" Custom settings

" Activate color scheme: Oceanic-next
" For Neovim 0.1.3 and 0.1.4
let $NVIM_TUI_ENABLE_TRUE_COLOR=1
" Or if you have Neovim >= 0.1.5
if (has("termguicolors"))
  set termguicolors
endif
" And the proper theme activation
syntax enable
" Let bolds and italics be enabled (if supported)
let g:oceanic_next_terminal_bold = 1
let g:oceanic_next_terminal_italic = 1
colorscheme OceanicNext

" Enable line numbers
set number

" Enable completion where available.
" pipenv install python-language-server
let g:ale_completion_enabled = 1
let g:ale_linters = {
\   'python': [
\       'pyls',
\   ],
\}

" And fix
" pipenv install yapf
let g:ale_fixers = {
\   'python': [
\	'yapf',
\       'isort',
\	'remove_trailing_lines',
\   ],
\}
" Enable fix on save
let g:ale_fix_on_save = 1

" Let deoplete-jedi handle async autocompletions
let g:jedi#completions_enabled = 0
" Use deoplete for autocompletions
let g:deoplete#enable_at_startup = 1
